setwd('/home-4/whou10@jhu.edu/scratch/Wenpin/GBM/res/')
d.integrated = readRDS('./seurat/addUMAP.rds')
library(Seurat)
library(ggplot2)
library(cowplot)
pca = d.integrated@reductions$pca@cell.embeddings
pcvar = apply(pca,2,var)
dir.create(paste0('./seurat/pca/'), recursive = T, showWarnings = F)
pdf('./seurat/pca/pcvar.pdf',height=4,width=4)
plot(pcvar,pch=20,xlab='num.PC',ylab='variance')
dev.off()
saveRDS(pca,paste0('./seurat/pca/pca.rds'))
source('/home-4/whou10@jhu.edu/scratch/Wenpin/raisin/proc/cluster.R')
cluster('/home-4/whou10@jhu.edu/scratch/Wenpin/GBM/res/seurat',hclu=F,useMNN=F,useUMAP=F,usePCA=T,num.PC=10)
